data = read.table("/Users/stuti/Downloads/household_power_consumption.txt", sep=";", header=T)
w =  which(data$Date == "1/2/2007" | data$Date == "2/2/2007")
m = data[w,]
m<- within(m, day <- paste(m$Date, m$Time, sep=" "))
m$day <- strptime(m$day, format="%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
plot(m$day, m$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
plot(m$day, m$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(m$day, m$Sub_metering_1, type="l", xlab="", ylab="Energy Sub Metering")
lines(m$day, m$Sub_metering_2, type="l", col="red")
lines(m$day, m$Sub_metering_3, type="l", col="blue")
legend("topright", legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), col=c("black", "blue", "red"))
plot(m$day, m$Global_reactive_power, type="l", xlab="datetime", ylab="global_reactive_power")